steps:
  # ================================
  # 1) Setup Python + deps
  # ================================
  - id: install-python-build-dependencies
    name: python:3.11
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        pip install --upgrade pip
        pip install build twine \
          keyring keyrings.google-artifactregistry-auth

  # ================================
  # 2) Testes básicos
  # ================================
  - id: validate-pipeline-imports
    name: python:3.11
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        pip install .
        python -c "from mlops_pipelines.pipelines.training import training_pipeline"
    waitFor: ["install-python-build-dependencies"]

  # ================================
  # 3) Build do pacote
  # ================================
  - id: build-python-package
    name: python:3.11
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        python -m build
    waitFor: ["validate-pipeline-imports"]

  # ================================
  # 4) Upload para Artifact Registry
  # ================================
  - id: publish-to-artifact-registry
    name: python:3.11
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        twine upload \
          --repository-url https://us-central1-python.pkg.dev/$PROJECT_ID/mlops-python/ \
          dist/*
    waitFor: ["build-python-package"]

options:
  logging: CLOUD_LOGGING_ONLY