substitutions:
  _PIPELINE_BUCKET: mlops-pipelines-definitions
  _PIPELINE_NAME: train_pipeline
  _VERSION_FILE: VERSION

steps:
  # 1️⃣ Instala dependências e compila pipeline
  - id: compile_pipeline
    name: python:3.10
    entrypoint: bash
    args:
      - -c
      - |
        pip install -r requirements.txt
        export PYTHONPATH=/workspace:$${PYTHONPATH}
        python scripts/compile_pipeline.py

  # 2️⃣ Publica no GCS (versionado)
  - id: publish_pipeline
    name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args:
      - -c
      - |
        VERSION=$(cat VERSION)
        gsutil cp dist/train_pipeline.json gs://$_PIPELINE_BUCKET/$_PIPELINE_NAME/v$${VERSION}/pipeline.json
    waitFor: ["compile_pipeline"]

options:
  logging: CLOUD_LOGGING_ONLY