steps:
  # ================================
  # 1) Setup Python + deps
  # ================================
  - name: python:3.11
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        pip install --upgrade pip
        pip install build twine \
          keyring keyrings.google-artifactregistry-auth

  # ================================
  # 2) Testes básicos
  # ================================
  - name: python:3.11
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        pip install .
        python -c "from mlops_pipelines.pipelines.training import training_pipeline"

  # ================================
  # 3) Build do pacote
  # ================================
  - name: python:3.11
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        python -m build

  # ================================
  # 4) Upload para Artifact Registry
  # ================================
  - name: python:3.11
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        twine upload \
          --repository-url https://us-central1-python.pkg.dev/$PROJECT_ID/mlops-python/ \
          dist/*
