substitutions:
  _PIPELINE_BUCKET: mlops-pipelines-definitions
  _PIPELINE_NAME: train_pipeline
  _VERSION_FILE: VERSION

steps:
  # 1️⃣ Instala dependências
  - id: install_dependencies
    name: python:3.10
    entrypoint: pip
    args: ["install", "-r", "requirements.txt"]

  # 2️⃣ Compila pipeline
  - id: compile_pipeline
    name: python:3.10
    entrypoint: python
    args: ["scripts/compile_pipeline.py"]
    waitFor: ["install_dependencies"]

  # 3️⃣ Lê versão e publica no GCS (versionado)
  - id: publish_pipeline
    name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args:
      - -c
      - |
        VERSION=$(cat VERSION)
        gsutil cp dist/train_pipeline.json gs://$_PIPELINE_BUCKET/$_PIPELINE_NAME/v$${VERSION}/pipeline.json
    waitFor: ["compile_pipeline"]

options:
  logging: CLOUD_LOGGING_ONLY