steps:
  # ================================
  # 1) Testes básicos
  # ================================
  - id: validate-pipeline-imports
    name: python:3.11
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        python -m pip install .
        python -c "from mlops_pipelines.pipelines.training import training_pipeline"

  # ================================
  # 2) Build do pacote
  # ================================
  - id: build-python-package
    name: python:3.11
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        python -m pip install --upgrade pip build
        python -m build --wheel
    waitFor: ["validate-pipeline-imports"]

  # ================================
  # 3) Upload para Artifact Registry
  # ================================
  - id: publish-to-artifact-registry
    name: python:3.11
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        python -m pip install --upgrade pip twine keyring keyrings.google-artifactregistry-auth
        twine upload \
          --repository-url https://us-central1-python.pkg.dev/$PROJECT_ID/mlops-python/ \
          dist/*
    waitFor: ["build-python-package"]

options:
  logging: CLOUD_LOGGING_ONLY
